// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://artxuczzmygrvyobcwvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFydHh1Y3p6bXlncnZ5b2Jjd3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjc0NzQsImV4cCI6MjA3MTYwMzQ3NH0.-HV-OVKdO1oSMFDqQgMir1fB-7Exckx6ITHFlQuZ_fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});